config/routes.rb
Rails.application.routes.draw do
  root to: "system_nodes#index"

  # resources :system_links
  # resources :system_nodes
  resources :system_nodes do
    resources :system_links
    resources :settings
    member do
      get 'graph'
    end
  end

  resources :system_links do

  end

  post '/system_nodes/:id/targets', to: 'system_nodes#add_target'

  post '/system_nodes/:id/sources', to: 'system_nodes#add_source'

  get '/system_nodes/:id/graph', to: 'system_nodes#graph_viz'
  get '/system_nodes/:id/d3', to: 'system_nodes#d3'
  # get "/status" => 'systemNodes#graph_viz', as: 'status'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/system_link.rb
class SystemLink < ApplicationRecord
  #belongs_to :system_node

  belongs_to :from_node, :class_name => 'SystemNode', :foreign_key => 'from_node_id'
  belongs_to :to_node, :class_name => 'SystemNode', :foreign_key => 'to_node_id'
end

app/controllers/system_links_controller.rb
class SystemLinksController < ApplicationController
  before_action :set_system_link, only: [:show, :edit, :update, :destroy]

  # GET /system_links
  # GET /system_links.json
  def index
    @system_links = SystemLink.all
  end

  # GET /system_links/1
  # GET /system_links/1.json
  def show
  end

  # GET /system_links/new
  def new
    @system_link = SystemLink.new
  end

  # GET /system_links/1/edit
  def edit
  end


  def create
    @list = List.find(params[:list_id])
    @task = @list.tasks.new(task_params)
    if @task.save
      redirect_to list_path(@task.list)
    else
      render :new
    end
  end

  # POST /system_links
  # POST /system_links.json
  def create
    @system_node = SystemNode.find(params[:system_node_id])
    @system_link = @system_node.targets.new(system_link_params)
    # @system_link = SystemLink.new(system_link_params)

    respond_to do |format|
      if @system_link.save
        format.html { redirect_to @system_link, notice: 'System link was successfully created.' }
        format.json { render :show, status: :created, location: @system_link }
      else
        format.html { render :new }
        format.json { render json: @system_link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /system_links/1
  # PATCH/PUT /system_links/1.json
  def update
    respond_to do |format|
      if @system_link.update(system_link_params)
        format.html { redirect_to @system_link, notice: 'System link was successfully updated.' }
        format.json { render :show, status: :ok, location: @system_link }
      else
        format.html { render :edit }
        format.json { render json: @system_link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /system_links/1
  # DELETE /system_links/1.json
  def destroy
    # @system_node = SystemNode.find(set_system_link)
    # @target = SystemLink.find(set_system_link)
    # @source = SystemLink.find(set_system_link)
    # @system_node.to_node_id.destroy
    # @system_node = SystemNode.find(params[:id])
    # SystemNode.joins(:system_links).where(system_link: { id: @system })
    @system_link = SystemLink.find(params[:id])

    if @system_link.destroy
      respond_to do |format|
        format.html { redirect_to system_nodes_path, notice: 'System link was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { redirect_to edit_system_node_path, notice: 'Error while destroying' }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_system_link
      # binding.pry
      # @system_node = SystemNode.find(params[:system_node_id])
      @system_link = SystemLink.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def system_link_params
      params.fetch(:system_link, {})
    end
end

app/helpers/system_links_helper.rb
module SystemLinksHelper
end

app/views/system_links/_form.html.erb
<%= form_with(model: system_link, local: true) do |form| %>
  <% if system_link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(system_link.errors.count, "error") %> prohibited this system_link from being saved:</h2>

      <ul>
      <% system_link.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
<%= simple_form_for @system_link do |f| %>
  <%= f.input :system_link do %>
    <%= f.select :system_link, SystemLink.all.map { |r| [r.name, r.id, { class: r.targets.from_node_id }] }, include_blank: true %>
  <% end %>
<% end %>



<%= simple_form_for [@system_node, @system_link] do |form| %>
    <%= form.association :targets, collection: SystemNode.all, prompt: "Choose a System Target" %>
<% end %>

<%= simple_form_for [@system_node, @system_link] do |form| %>
    <%= form.association :sources, collection: SystemNode.all, prompt: "Choose a System Source" %>
<% end %>

app/views/system_links/edit.html.erb
<h1>Editing System Link</h1>

<%= render 'form', system_link: @system_link %>

<%= link_to 'Show', @system_link %> |
<%= link_to 'Back', system_links_path %>
<%= link_to 'Edit Settings for Node', system_links_path %>

app/views/system_links/index.html.erb
<p id="notice"><%= notice %></p>

<h1>System Links</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @system_links.each do |system_link| %>
      <tr>
        <td><%= link_to 'Show', system_link %></td>
        <td><%= link_to 'Edit', edit_system_link_path(system_link) %></td>
        <td><%= link_to 'Destroy', system_link, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New System Link', new_system_link_path %>

<% @system_links.each do |system_link| %>
  <h2><%= system_link.from_node_id %></h2>
  <h3><%= link_to 'Show', system_link %></h3>
  <h3><%= link_to 'Edit', edit_system_link_path(system_link) %></h3>
  <h3><%= link_to 'Destroy', system_link, method: :delete, data: { confirm: 'Are you sure?' } %></h3>
<% end %>

app/views/system_links/new.html.erb
<h1>New System Link</h1>

<%= render 'form', system_link: @system_link %>

<%= link_to 'Back', system_links_path %>

app/views/system_links/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_system_link_path(@system_link) %> |
<%= link_to 'Back', system_links_path %>