config/routes.rb
Rails.application.routes.draw do
  root to: "system_nodes#index"

  # resources :system_links
  # resources :system_nodes
  resources :system_nodes do
    resources :system_links
    resources :settings
    member do
      get 'graph'
    end
  end

  resources :system_links do

  end

  post '/system_nodes/:id/targets', to: 'system_nodes#add_target'

  post '/system_nodes/:id/sources', to: 'system_nodes#add_source'

  get '/system_nodes/:id/graph', to: 'system_nodes#graph_viz'
  get '/system_nodes/:id/d3', to: 'system_nodes#d3'
  # get "/status" => 'systemNodes#graph_viz', as: 'status'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/system_node.rb
class SystemNode < ApplicationRecord
  has_many :settings

  has_many :target_links, :foreign_key => :from_node_id,
          :class_name => 'SystemLink'
  has_many :targets, :through => :target_links,
          :source => :to_node, dependent: :destroy

  has_many :source_links, :foreign_key => :to_node_id,
           :class_name => 'SystemLink'
  has_many :sources, :through => :source_links,
           :source => :from_node, dependent: :destroy

  def get_setting(key)
    for setting in self.settings
      return setting.value if setting.key==key
    end
    return nil
  end

  def dot2(attrs_to_show=['github','host'])
    g = Graph.new
    g.attrs_to_show = attrs_to_show
    g.add_node(self, 4, 4)
    g.to_dot
  end

  def node_label(attr_names)
    #this will make an html label in dot syntax
    #with the node name on the first line and a row for
    #any of the provided attr_names if and only if that node has a value
    #for that parameter
    node_label = "<#{self.name}<br/>"

    attr_names.each {|k|
      v = self.get_setting(k)
      if v
        node_label+="#{k}: #{v}"
      end
    }
    node_label+=">"
  end

  # attrs_to_show is hard coded or default? here in the params
  def dot(attrs_to_show=['github','host'])
    return dot2(attrs_to_show=['github','host'])

    # creation of initial self node
    nodes = {self.id=>self}
    # creation of nodes from sources
    self.sources.each do |n|
      nodes[n.id] = n
    end
    # creation of nodes from targets
    self.targets.each do |n|
      nodes[n.id]=n
    end

  # creation of dot language nodes list from nodes
    nodes_list = nodes.map {|id,node|
      # output example: "node_19 [label=<Reporter<br/>>]"
      "node_#{id} [label=#{node.node_label(attrs_to_show)} fillcolor=\"#d62728\"]"
    }
    # creation of edges list in dot notation
    edges_list = self.sources.map { |n| "node_#{n.id} -> node_#{self.id}" }
    edges_list += self.targets.map { |n| "node_#{self.id} -> node_#{n.id} " }


    "digraph {
        #{(nodes_list + edges_list).join(";\n")};
    }"
  end

  def sample_dot
    'digraph {
        graph [label="Click on a node or an edge to delete it" labelloc="t", fontsize="20.0" tooltip=" "]
        node [style="filled"]
        Node1 [id="NodeId1" label="N1" fillcolor="#d62728"]
        Node2 [id="NodeId2" label="N2" fillcolor="#1f77b4"]
        Node3 [id="NodeId3" label="N3" fillcolor="#2ca02c"]
        Node4 [id="NodeId4" label="N4" fillcolor="#ff7f0e"]
        Node1 -> Node2 [id="EdgeId12" label="E12"]
        Node1 -> Node3 [id="EdgeId131" label="E13"]
        Node2 -> Node3 [id="EdgeId23" label="E23"]
        Node3 -> Node4 [id="EdgeId34" label="E34"]
    }'
  end

  def hello
    "hello"
  end

  def method_missing(m, *args, &block)
    for s in self.settings
      return s.value if s.key==m.to_s
    end
    puts "There is no method #{m}"
    return nil
  end


  def node_settings
    '<% @system_nodes.each do |system_node| %>
      <div class="col-md-4">
        <h2><%= system_node.name %></h2>  </br>
        <%= system_node.address %> </br>
        <%= system_node.description %> </br>
        settings: <%= system_node.settings.count %> </br>
        sources: <%= system_node.sources.count %> </br>
        targets: <%= system_node.targets.count %> </br>
        <%= link_to "Show", system_node %>
        <%= link_to "Edit", edit_system_node_path(system_node) %>
        <%= link_to "Destroy", system_node, method: :delete, data: { confirm: "Are you sure?" } %>
        <div class="node-settings">
          <table class="table">
           <tr>
             <th>Key:</th>
             <th>Value:</th>
           </tr>
          <% system_node.settings.each do |setting| %>
               <tr>
                 <td>Key: <%= setting.key %></td>
                 <td>Value: <%= setting.value %></td>
               </tr>
            <% end %>
          </table>
        </div>
      </div>

    <% end %>'

  end

  def self.query_by_type(type_name)
    SystemNode.joins(:settings).where("settings.key='type:#{type_name}'")
  end

  def self.import_yaml(yaml_path)

    data = YAML.load_file(yaml_path)

    nodes = data["nodes"]

    puts "File has #{nodes.count} nodes"

    # nodes.each { |k, v| puts "Node name: ${k}\n\t properties: #{v}" }
    nodes.each { |k, v| puts "The hash key is #{k} and the value is #{v}."}
    nodes.each do |nodekey, nodevalue|
      puts "The hash key is #{nodekey} and the value is #{nodevalue}."
      node = SystemNode.find_or_create_by(name: nodekey.to_s)

      nodevalue.each do |settingkey, settingvalue|
        if settingkey != 'targets' && settingkey != "sources"
          #node = SystemNode.find_or_create_by(name: nodekey.to_s)
          setting = node.settings.find_or_create_by(key: settingkey)
          if setting.value && setting.value != settingvalue
            puts "Changing node #{node.id} #{settingkey} from #{setting.value} to #{settingvalue}"
          end
          if setting.value != settingvalue
            setting.value = settingvalue
            setting.save!
          end
          puts "The setting key for #{nodekey} is #{settingkey} and the setting value is #{settingvalue}."
        else
          #dealing with targets
          if settingvalue.class == Array
            #at this point settingvalue is the array of Hashes of target node
            settingvalue.each do |linked_node_hash|
              #given our convention in the yaml file,
              #each key of linked_node_hash will be a node name
              #of the target, and the value of the hash will be a hash of any
              # key value pairs listed under the target node name in the yaml
              puts "unexpected format" if linked_node_hash.count>1

              linked_node_name = linked_node_hash.keys[0]

              linked_node = SystemNode.find_or_create_by(name: linked_node_name)

              if settingkey == "targets"
                link_types = node.target_links
                from_node_id = node.id
                to_node_id = linked_node.id
              else
                link_types = node.source_links
                from_node_id = linked_node.id
                to_node_id = node.id
              end
              link_types.find_or_create_by(from_node_id: from_node_id, to_node_id: to_node_id)
            end
          else
            puts "warning, targets for #{node.name} was not an array, skipping"
          end
        end
      end
    end
  end
end

app/models/system_nodes_helper.rb
module SystemNodesHelper
  def routeId(var)
    binding.pry
    var.to_i
  end
end

app/controllers/system_nodes_controller.rb
class SystemNodesController < ApplicationController
  before_action :set_system_node, only: [:show, :edit, :update, :destroy]

  def index
    if params["type"]
      @system_nodes = SystemNode.query_by_type(params["type"])
    else
      @system_nodes = SystemNode.all
    end
  end

  def show
    @system_node = SystemNode.find(params[:id])
  end

  def new
    @system_node = SystemNode.new
  end

  def edit
    @system_node = SystemNode.find(params[:id])
    @source = SystemLink.where(from_node_id: @system_node.id)
    @target = SystemLink.where(to_node_id: @system_node.id)
  end

  def create
    @system_node = SystemNode.new(system_node_params)

    respond_to do |format|
      if @system_node.save
        format.html { redirect_to edit_system_node_path(@system_node), notice: 'System node was successfully created.' }
        format.json { render :show, status: :created, location: @system_node }
      else
        format.html { render :new }
        format.json { render json: @system_node.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /system_nodes/1
  # PATCH/PUT /system_nodes/1.json
  def update
    respond_to do |format|
      if @system_node.update(system_node_params)
        format.html { redirect_to edit_system_node_path(@system_node), notice: 'System node was successfully updated.' }
        format.json { render :show, status: :ok, location: @system_node }
      else
        format.html { render :edit }
        format.json { render json: @system_node.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /system_nodes/1
  # DELETE /system_nodes/1.json
  def destroy
    @system_node.destroy
    respond_to do |format|
      format.html { redirect_to system_nodes_url, notice: 'System node was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def add_target()
    source_id = request.params['id']
    l = SystemLink.create(from_node_id: source_id, to_node_id: request.params['target_node_id'])
    redirect_to action: "edit", id: source_id
  end

  def add_source()
    target_id = request.params['id']
    l = SystemLink.create(to_node_id: target_id, from_node_id: request.params['source_node_id'])
    redirect_to action: "edit", id: target_id
  end

  def graph
    @system_node = SystemNode.find(params[:id])
    @system_nodes = SystemNode.all
  end

  def d3
    @system_node = SystemNode.find(params[:id])
    @system_nodes = SystemNode.all
  end

  def status
    @System_node = SystemNode.where(:id => params[:find_id])
     respond_to do |format|
         format.js
     end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_system_node
      @system_node = SystemNode.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def system_node_params
      params.require(:system_node).permit(:name, :address, :description, :from_node_ids, :to_node_ids )
    end

    def update_params
      params.require(:system_node).permit(:from_node_ids => [],:to_node_ids => [])
    end

end

app/views/system_nodes/_bar_graph.html.erb
<meta charset="utf-8">
<style> /* set the CSS */


svg {border: lightgrey 1px solid;
      padding: 20px;}
</style>
<body>

<!-- load the d3.js library -->
<!-- <script src="https://d3js.org/d3.v5.min.js"></script> -->
<script type="text/javascript">
var jsonRectangles = [
  { "x_axis": 0, "y_axis": 10, "height": 25, "width":40, "color" : "#41ebf4" },
  { "x_axis": 0, "y_axis": 40, "height": 25, "width":200, "color" : "#4286f4" },
  { "x_axis": 0, "y_axis": 70, "height": 25, "width":70, "color" : "#f44194" }];

 var max_x = 0;
 var max_y = 0;

for (var i = 0; i < jsonRectangles.length; i++) {
  var temp_x, temp_y;
  var temp_x = jsonRectangles[i].x_axis + jsonRectangles[i].width;
  var temp_y = jsonRectangles[i].y_axis + jsonRectangles[i].height;

  if ( temp_x >= max_x ) { max_x = temp_x; }

  if ( temp_y >= max_y ) { max_y = temp_y; }
}

var svgContainer = d3.select("body").append("svg")
                                    .attr("width", max_x)
                                    .attr("height", max_y)

var rectangles = svgContainer.selectAll("rect")
                             .data(jsonRectangles)
                             .enter()
                             .append("rect");

var rectangleAttributes = rectangles
                          .attr("x", function (d) { return d.x_axis; })
                          .attr("y", function (d) { return d.y_axis; })
                          .attr("height", function (d) { return d.height; })
                          .attr("width", function (d) { return d.width; })
                          .style("fill", function(d) { return d.color; });
</script>



    <!-- cx - The x-axis coordinate of the center of the circle.
    cy - The y-axis coordinate of the center of the circle.
    r - The radius of the circle. -->

</body>

app/views/system_nodes/_neighbor_list.erb
<div class="table-style">
  <table class="table table-hover">
    <tr>
      <th align="left">System</th>
      <th align="left">Address</th>
      <th align="left">Description</th>
    </tr>
    <% if nodes %>
  <% nodes.each do |target| %>
  <tr>
    <td><%= link_to target.name, edit_system_node_path(target) %></td>
    <td><%= target.address %></td>
    <td><%= target.description %></td>
      <td><%= link_to 'Destroy', target, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
  <% end %>
  <% else %>
  <tr><td>None</td><tr>
  <% end %>
</table>
</div>

app/views/system_nodes/_settings_table.html.erb
<table class="table">
  <div class="node-settings">
    <th>Settings for <%= @system_node.name %> </th>
    <% @system_node.settings.each do |s| %>
      <tr><td><%= s.key %></td><td><%= s.value %></td><td><%= link_to "Edit", edit_system_node_setting_path(@system_node, s) %> <%= link_to 'Destroy', system_node_setting_path(@system_node,s), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </div>
</table>

app/views/system_nodes/_source_links_list.erb
<div class="table-style">
  <table class="table table-hover">
    <tr>
      <th align="left">System</th>
      <th align="left">Address</th>
      <th align="left">Description</th>
    </tr>
    <% if links %>
    <% puts links %>
  <% links.each do |link| %>
  <% node = link.from_node %>
  <% if node %>
  <tr>
    <% puts links %>
    <% puts link.from_node_id %>

    <td><%= link_to node.name, edit_system_node_path(node) %></td>
    <td><%= node.address %></td>
    <td><%= node.description %></td>
      <td>
        <a data-confirm="Are you sure?" rel="nofollow" data-method="delete" href="/system_links/<%=link.id %>">Destroy</a>
      </td>
  </tr>
  <% end %>
  <% end %>
  <% else %>
  <tr><td>None</td><tr>
  <% end %>
</table>
</div>

app/views/system_nodes/_status.js.erb
console.log("status page!!!");
// console.log(this.);
// $('#item<%= @item.id %>').remove()
// $('.case-detail').text('<%= j render("settings_table") %>')

app/views/system_nodes/_target_links_list.erb
<div class="table-style">
  <table class="table table-hover">
    <tr>
      <th align="left">System</th>
      <th align="left">Address</th>
      <th align="left">Description</th>
    </tr>
    <% if links %>
  <% links.each do |link| %>
  <% node = link.to_node %>
  <% if node %>
  <tr>
    <td><%= link_to node.name, edit_system_node_path(node) %></td>
    <td><%= node.address %></td>
    <td><%= node.description %></td>

      <td><a data-confirm="Are you sure?" rel="nofollow" data-method="delete" href="/system_links/<%=link.id %>">Destroy</a></td>
  </tr>
  <% else %>
  <tr><%= link %></tr>
  <% end %>
  <% end %>
  <% else %>
  <tr><td>None</td><tr>
  <% end %>
</table>
</div>

app/views/system_nodes/edit.html.erb
<%
  nodes = local_assigns[:nodes]
%>
 <h1><%= @system_node.name %></h1>
<button class="btn btn-info">
  <%= link_to 'Graph', 'graph', :class => 'btn', description: 'Graph Time' %>
</button>
<div class="page">
  <div class="col-md-12">
    <div class="system-node-form col-md-6">
      <h3><%= @system_node.name %></h3>
      <%= render 'form', system_node: @system_node %>
    </div>
    <div class="col-md-6">
      <h3><%= @system_node.name %> Settings</h3>
      <%= render 'settings_table', system_node: @system_node %>
      <button class=" btn btn-info"> <%= link_to 'New Setting for Node', new_system_node_setting_path(@system_node) %> </button>
    </div>
  </div>
  <div class="break">

  </div>

  <div class="sources-targets col-md-12">
      <h1>Add a Connection for <%= @system_node.name %> </h1>
      <div class="sources-list col-md-6">
        <h2>Sources</h2>
        <%= render 'source_links_list', links: @system_node.source_links.to_a %>

          <div class="form-group">
            <%= form_tag("/system_nodes/#{@system_node.id}/sources", method: "post") do %>
              <select class="form-control" id="source_node_id" name="source_node_id">
              <%= options_for_select(SystemNode.all.map { |n| [n.name, n.id] }) %>
              </select>
              <button class=" btn btn-info"> <%= submit_tag("Add Source") %> </button>
            <% end %>
          </div>
      </div>
      <div class="targets-list col-md-6">
        <h2>Targets</h2>
        <%= render 'target_links_list', links: @system_node.target_links.to_a %>
          <div class="form-group">
            <%= form_tag("/system_nodes/#{@system_node.id}/targets", method: "post") do %>
              <select class="form-control" id="target_node_id" name="target_node_id">
              <%= options_for_select(SystemNode.all.map { |n| [n.name, n.id] }) %>
              </select>
              <button class=" btn btn-info"> <%= submit_tag("Add Target") %></button>
            <% end %>
          </div>
      </div>
  </div>
</div>

app/views/system_nodes/graph.html.erb
<h1>Graph for <%= @system_node.name %></h1>
<div class="inspector">
  <div class="case-detail">
  </div>
  <h2>Status Bar</h2>
  <div class="bar-graph">
  </div>
</div>

<div id="graph" style="text-align: center;"></div>
<script>
console.log('<%= @system_node.hello %>');

// All of the dot code in a string
var dotSrc = `<%= @system_node.dot.html_safe %>`;

// the graph itself in a div
var graphviz = d3.select("#graph").graphviz();





function handleNodeClick() {
  function loadDetailPane(routeId) {

    $.getJSON("/system_nodes/" + routeId).done(renderDetailPane);
    console.log(dotElement);
    console.log("route id" + routeId);
  }

  function renderDetailPane(data) {
  //   var content = $('<div/>');
  //   var label1 = $('<h2/>');
  //   var label2 = $('<h3/>');
  //   var label3 = $('<h5/>');
  //   var editLink = $('<%= link_to graph_system_node_path(@system_node) %>');
  //   var editLink = $('<a href="/system_nodes/' + routeId + '/edit">edit</a>');
  //   console.log(data.settings);
  //
  //   // data = {name: "adfadf", updated_at:"adfadfa" ,
  //   // settings: {"mysettingnamex":"davalueofx"},
  //   // stats:{"mycount1":2, "someothercount":4}};
  //   label1.append(data.name)
  //   label2.append(data.id)
  //   label3.append(data.settings)
  //   label1.appendTo(content);
  //   label2.appendTo(content);
  //   label3.appendTo(content);
  //   editLink.appendTo(content);
  //
  //   for (var key in data.settings) {
  //     // skip loop if the property is from prototype
  //     if (!data.settings.hasOwnProperty(key)) continue;
  //     var obj = data.settings[key];
  //     for (var prop in obj) {
  //         // skip loop if the property is from prototype
  //         if(!obj.hasOwnProperty(prop)) continue;
  //           if(prop.toString() == "key" || prop.toString() == "value"){
  //           label3.append(prop + " : " + obj[prop] + '<br>')
  //           label3.appendTo(content)
  //           }else {
  //             console.log("wrong prop");
  //             console.log(prop.toString());
  //           }
  //     }
  // }
  // table view
  // document.getElementsByClassName('case-detail').innerHTML = "";
  // $('.case-detail').removeChild();
  var graphLink = $('<a href="/system_nodes/' + routeId + '/graph">Graph</a>');
  var editLink = $('<a href="/system_nodes/' + routeId + '/edit">Edit</a>');
  var content = $('<div/>');
  var table = $('<table/>');
  var tableRow = $('<tr/>');
  var tableData = $('<td/>');
  var label1 = $('<h2/>');
  var label2 = $('<h3/>');
  var label3 = $('<h5/>');

  console.log(data.settings);

  label1.append(data.name)
  // label2.append(data.id)
  label3.append(data.settings)
  label1.appendTo(content);
  // label2.appendTo(content);
  label3.appendTo(content);
  content.appendTo(".case-detail");
  table.appendTo(content);
  tableRow.appendTo(table);
    // tableData.appendTo(tableRow);
  graphLink.appendTo(content);
  editLink.appendTo(content);
    for (var key in data.settings) {
      // skip loop if the property is from prototype
      if (!data.settings.hasOwnProperty(key)) continue;
      var obj = data.settings[key];
      for (var prop in obj) {
          // skip loop if the property is from prototype
          if(!obj.hasOwnProperty(prop)) continue;
            if(prop.toString() == "key" || prop.toString() == "value"){
            // label3.append(prop + " : " + obj[prop] + '<br>')
            // table.append()
            var td = $('<tr>' + '<td>' + obj[prop] + '</td>' + '</tr>')
            td.appendTo(table)
            // tableRow.html('<td>' + prop + '</td>' + '<td>' + obj[prop] + '</td>')
            console.log("loop counter");

            // tableRow.append('<td>' + obj[prop] + '</td>' + '</tr>')
            // table.append('</tr>')

            // tableData.append(obj[prop])
            // tableData.appendTo(table)
            }else {
              console.log("wrong prop");
              console.log(prop.toString());
            }
      }
    }
  $('.case-detail').empty();
  $('.case-detail').append(content);

  }

  // On click select all titles of this
    var title = d3.select(this).selectAll('title').text().trim();
  // On click select all text of this
    var text = d3.select(this).selectAll('text').text();
  // On click select id of this
    var id = d3.select(this).attr('id');
  // On click select class of this
    var class1 = d3.select(this).attr('class');
  // Replace titles with arrows
    dotElement = title.replace('->',' -> ');

    // Console log current element id, class, title, text and dotElement
    console.log('Element id="%s" class="%s" title="%s" text="%s" dotElement="%s"', id, class1, title, text, dotElement);

    console.log('NODE ID IS: id="%s"', id);

    // var node = (this).getBoundingClientRect()
    // var positionLeft = node.left - 180;
    // var positionTop = node.top;
    // console.log("Left position here " + node.left);
    // console.log("Top position here " + node.top);
    //
    // $('body').append('<div id="close" class="graph-settings" style="left:'+ positionLeft + 'px; top:' + positionTop + 'px;"><a>x</a></div>')

    var routeId = dotElement.replace('node_','');
console.log("fancy" + routeId);

  function barGraph() {

    var dataImport = [3, 4, 39, 15, 4, 65, 15, 20, 19, 5, 7, 9, 31, 10];

    var daysCounted = dataImport.map(function(element) {
      return element = dataImport.length;
    });

    var svgContainer = d3.select(".bar-graph").append("svg")
                                        .attr("width", 250)
                                        .attr("height", 450)

    var rectangles = svgContainer.selectAll("rect")
                                 .data(dataImport)
                                 .enter()
                                 .append("rect");
    var y = (-10)
    var rectangleAttributes = rectangles
                              .attr("x", function (d) { return 20; })
                              .attr("y", function (d) { return y = y + 30; })
                              .attr("height", function (d) { return 25; })
                              .attr("width", function (d) { return d * 3; })
                              .style("fill", function(d) {
                                  if (d > 60) {return '#fe482f'}
                                  else if (d > 30 && d < 59) {return '#ff7b11'}
                                  else 	{ return '#00bcd6' }
                              ;})

                          var xscale = d3.scaleLinear()
                             .domain([0, d3.max(dataImport)])
                             .range([30, 250]);

                          var yscale = d3.scaleLinear()
                             .domain([0, d3.max(daysCounted)])
                             // y axis [height, position]
                             .range([425, 0]);
                          var x_axis = d3.axisTop()
                              .scale(xscale);
                          var y_axis = d3.axisLeft()
                              .scale(yscale);
                          svgContainer.append("g")
                              .attr("transform", "translate(20, 30)")
                              .call(y_axis);
                              var xAxisTranslate = 20;
                          svgContainer.append("g")
                             .attr("transform", "translate(-10, " + xAxisTranslate  +")")
                             .call(x_axis)

  }
    // $('a').on('click', function(){
    //   $(this).closest("#close").remove();
    // });

    loadDetailPane(routeId);
    $('.bar-graph').empty();
    barGraph();
}

// function to render dot code using dotSrc
function render(dotSrc) {
    console.log('DOT source =', dotSrc);

    // Split incoming string by line
    var dotSrcLines = dotSrc.split('\n');

    // Transition animation
    transition1 = d3.transition()
        .delay(100)
        .duration(1000);

    // applying transitions to the graph
    graphviz
        .transition(transition1)
        .renderDot(dotSrc);

    // Grabbing all nodes and edges
    nodes = d3.selectAll('.node,.edge');

    // On click function for node change
    nodes.on("click", handleNodeClick);
}
render(dotSrc);

</script>

app/views/system_nodes/graph.js.erb
$('#show_graph_viz').on('click', function() { console.log("jQuery fired")
$('body').append("<%= render 'layouts/shared/settings' %>")
});

app/views/system_nodes/graph_viz.js.erb
$('#show_graph_viz').on('click', function() { console.log("jQuery fired")
$('body').append("<%= render 'layouts/shared/settings' %>")
});

app/views/system_nodes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>System Nodes</h1>


  <ul class="nav nav-tabs" id="myTab" role="tablist">
    <li class="nav-item">
      <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">Nodes Display</a>
    </li>
    <li class="nav-item active">
      <a class="nav-link active" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="true">Nodes List</a>
    </li>

  </ul>
  <div class="tab-content" id="myTabContent">
    <div class="tab-pane active page" id="profile" role="tabpanel" aria-labelledby="profile-tab">

      <table>
        <% @system_nodes.sort_by {|n| n.name}.each do |system_node| %>
          <tr><td><%# = link_to system_node.name, system_node_graph_path(system_node)%>
            <a href="/system_nodes/<%= system_node.id %>/edit"><%= system_node.name %></a>

          </td><tr>
        <% end %>
      </table>

    </div>
    <div class="tab-pane fade show" id="home" role="tabpanel" aria-labelledby="home-tab">
      <%= render 'layouts/shared/settings' %>
    </div>


  </div>

app/views/system_nodes/new.html.erb
<h1>New System Node</h1>

<div class="page">
  <%= render 'form', system_node: @system_node %>
</div>

app/views/system_nodes/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_system_node_path(@system_node) %> |
<%= link_to 'Back', system_nodes_path %>


<h1><%= @system_node.name %></h1>

<% if !@system_links.nil? %>
  <h4>Here are the system links for <%=@system_node.name%>:</h4>

  <ul>
    <% @system_links.each do |link| %>
      <li>

        <strong><%= link.name %></strong>

        <%= link_to "Edit", edit_system_node_system_link_path(@system_node, link) %> |
        <%= link_to "Delete", system_node_system_link_path(@system_node, link),
                                 :data => {:confirm => "Are you sure?",
                                                :method => "delete"} %>
      </li>
<% end %>
<% end %>