config/routes.rb
Rails.application.routes.draw do
  root to: "system_nodes#index"

  # resources :system_links
  # resources :system_nodes
  resources :system_nodes do
    resources :system_links
    resources :settings
    member do
      get 'graph'
    end
  end

  resources :system_links do

  end

  post '/system_nodes/:id/targets', to: 'system_nodes#add_target'

  post '/system_nodes/:id/sources', to: 'system_nodes#add_source'

  get '/system_nodes/:id/graph', to: 'system_nodes#graph_viz'
  get '/system_nodes/:id/d3', to: 'system_nodes#d3'
  # get "/status" => 'systemNodes#graph_viz', as: 'status'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/shared/_footer.html.erb
<footer>
  <div class="footer-info">
    <h2>Genops Application</h2>
  </div>
</footer>

app/views/layouts/shared/_graphsettings.js.erb
 console.log("jQuery fired")
$('body').append("<%= render 'layouts/shared/settings' %>")

app/views/layouts/shared/_nav.html.erb
<nav class="navbar navbar-dark bg-dark">

  <span class="navbar-text">
    <a><%= link_to "GENOPS", system_nodes_path %></a>
  </span>
  <span class="navbar-text">
    <a><%= link_to "Show All Systems", system_nodes_path %></a>
  </span>
  <span class="navbar-text">
    <a><%= link_to "Systems", system_nodes_path(type:"system")%></a>
  </span>
  <span class="navbar-text">
    <a><%= link_to "Cases", system_nodes_path(type:"case")%></a>
  </span>
  <span class="navbar-text">
    <a><%= link_to "Pipelines", system_nodes_path(type:"pipeline")%></a>
  </span>
  <span class="navbar-text">
    <a><%= link_to "Workflows", system_nodes_path(type:"workflow")%></a>
  </span>
  <span class="navbar-text">
    <a><%= link_to "Create System", new_system_node_path %></a>
  </span>
</nav>

app/views/layouts/shared/_settings.html.erb
<% @system_nodes.each do |system_node| %>
  <div class="col-md-12">
    <h3><%= system_node.name %></h3>  </br>
    <%= system_node.address %> </br>
    <%= system_node.description %> </br>
    settings: <%= system_node.settings.count %> </br>
    sources: <%= system_node.sources.count %> </br>
    targets: <%= system_node.targets.count %> </br>
    <%= link_to 'Show', system_node %>
    <%= link_to 'Edit', edit_system_node_path(system_node) %>
    <%= link_to 'Destroy', system_node, method: :delete, data: { confirm: 'Are you sure?' } %>
    <div class="node-settings">
      <table class="table">
       <tr>
         <th>Settings:</th>
       </tr>
      <% system_node.settings.each do |setting| %>
           <tr>
             <td> <h4><%= setting.key %></h4> </td>
             <td><%= setting.value %></td>
           </tr>
        <% end %>
      </table>
    </div>
  </div>

<% end %>