config/routes.rb
Rails.application.routes.draw do
  root to: "system_nodes#index"

  # resources :system_links
  # resources :system_nodes
  resources :system_nodes do
    resources :system_links
    resources :settings
    member do
      get 'graph'
    end
  end

  resources :system_links do

  end

  post '/system_nodes/:id/targets', to: 'system_nodes#add_target'

  post '/system_nodes/:id/sources', to: 'system_nodes#add_source'

  get '/system_nodes/:id/graph', to: 'system_nodes#graph_viz'
  get '/system_nodes/:id/d3', to: 'system_nodes#d3'
  # get "/status" => 'systemNodes#graph_viz', as: 'status'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/setting.rb
class Setting < ApplicationRecord
  belongs_to :system_node
  validates :key, uniqueness: {scope: :system_node_id}
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  before_action :set_setting, only: [:show, :edit, :update, :destroy]

  ActionController::Parameters.permit_all_parameters = true

  # GET /settings
  # GET /settings.json
  def index
    @system_node = SystemNode.find(params[:system_node_id])
    @settings = @system_node.settings
  end

  # GET /settings/1
  # GET /settings/1.json
  def show
  end

  # GET /settings/new
  def new
    @system_node = SystemNode.find(params[:system_node_id])
    @setting = @system_node.settings.new(setting_params)
    @system_nodes = SystemNode.all
    # @setting = Setting.new
  end

  # GET /settings/1/edit
  def edit
    @system_node = SystemNode.find(params[:system_node_id])
    @setting = Setting.find(params[:id])

    # system_node = SystemNode.find(params[:id])
    # @setting = Setting.find(params[system_node.id])
  end

  # POST /settings
  # POST /settings.json
  def create
    @system_node = SystemNode.find(params[:system_node_id])
    @setting = @system_node.settings.new()
#binding.pry
    @setting.key = params[:setting][:key]
    @setting.value = params[:setting][:value]
    @setting.location = params[:setting][:location]


    respond_to do |format|
      if @setting.save
        format.html { redirect_to edit_system_node_path(@system_node), notice: 'Setting was successfully created.' }
        format.json { render :show, status: :created, location: @setting }
      else
        format.html { render :new }
        format.json { render json: @setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /settings/1
  # PATCH/PUT /settings/1.json
  def update

    respond_to do |format|

      key = params["setting"]["key"]
      value = params["setting"]["value"]
      @setting.key = key
      @setting.value = value
      @setting.location = params["setting"]["location"]
      if @setting.save!

        format.html { redirect_to edit_system_node_path(@setting.system_node_id), notice: 'Setting was successfully updated.' }
        format.json { render :show, status: :ok, location: @setting }
      else
        format.html { render :edit }
        format.json { render json: @setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /settings/1
  # DELETE /settings/1.json
  def destroy
    system_node_id = @setting.system_node_id
    @setting.destroy
    respond_to do |format|
      format.html { redirect_to edit_system_node_path(system_node_id), notice: 'Setting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_setting
      @setting = Setting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def setting_params
        params.permit(:setting, :key, :value, :location) #, :key, :value, :location, #:system_node_id )
    end
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/views/settings/_form.html.erb
<div class="col-md-10">
  <%= simple_form_for [@system_node, @setting] do |form| %>
    <% if setting.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(setting.errors.count, "error") %> prohibited this setting from being saved:</h2>

        <ul>
        <% setting.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">

      <%#= form.input :system_node_id, collection: @system_nodes, class: 'form-control', label: 'Select which Node this Setting is for: ' %>

    </div>


    <div class="field">
      <%= form.label :key, class: 'control-label' %>
      <%= form.text_field :key, class: 'form-control' %>
    </div>

    <div class="field">
      <%= form.label :value, class: 'control-label' %>
      <%= form.text_field :value, class: 'form-control' %>
    </div>

    <div class="field">
      <%= form.label :location, class: 'control-label' %>
      <%= form.text_field :location, class: 'form-control' %>
    </div>


    <div class="actions">
      <button class=" btn btn-info"> <%= submit_tag("Add Setting") %></button>
      
    </div>
  <% end %>
</div>

app/views/settings/edit.html.erb
<h1>Editing Setting</h1>

<%= render 'form', setting: @setting %>

<%= link_to 'Show', system_node_setting_path(@setting) %> |

app/views/settings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Settings</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @settings.each do |setting| %>
      <tr>
        <td><%= link_to 'Show', setting %></td>
        <td><%= link_to 'Edit', edit_setting_path(setting) %></td>
        <td><%= link_to 'Destroy', setting, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Setting', new_setting_path %>

app/views/settings/new.html.erb
<h1>New Setting</h1>

<%= render 'form', setting: @setting %>

<%= link_to 'Back', edit_system_node_path(@system_node) %>

app/views/settings/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_system_node_setting_path(@system_node) %> |
<%= link_to 'Back', settings_path %>
Key: <%= @setting.key %>
Value: <%= @setting.value %>
Location: <%= @setting.location %>